// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// wireApp khởi tạo toàn bộ application với dependency injection
func wireApp() (*gin.Engine, error) {
	engine := provideGinEngine()
	return engine, nil
}

// wire.go:

// provideGinEngine tạo gin engine đơn giản
func provideGinEngine() *gin.Engine {
	return gin.New()
}
