# Local Development Configuration
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123postgres
  sslmode: disable

redis:
  host: localhost
  port: 6379

consul:
  address: localhost:8500

services:
  user_service:
    port: 50051
    db_name: user_service

  product_service:
    port: 50052
    db_name: product_service

  order_service:
    port: 50053
    db_name: order_service

api_gateway:
  port: 8080

api_gateway_huma:
  port: 8081
