name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]
        service:
          - user-service
          - order-service
          - product-service
          - api-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Show Go version
        run: go version

      - name: Tidy up go.mod
        run: go mod tidy
        working-directory: ${{ matrix.service }}

      - name: Build
        run: go build -v ./...
        working-directory: ${{ matrix.service }}

      - name: Test
        run: go test -v ./...
        working-directory: ${{ matrix.service }}
